version: "3.3"

services:
  worker:
    build: .
    image: conversation-bots
    container_name: conversation-bots
#    command: ["sleep", "10000"]
    volumes:
      - ./.env:/app/.env
      - ./config.json:/app/config.json
      - ./.tdlib:/app/.tdlib
